return error when when resolving request_uri fails
return the properly generated `invalid_request_uri` error response
instead of continuing handling the (by then faulty) request which would
return in the following exception:

```
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/oic-0.14.0-py3.6.egg/oic/oic/provider.py",
line 665, in filter_request
    before = req.to_dict()
AttributeError: 'Response' object has no attribute 'to_dict'
```

see: openid-certification/oidctest#10

Signed-off-by: Hans Zandbelt <hans.zandbelt@zmartzone.eu>